### ISSUE TITLE
Container for testing and development

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/pgpg#19]
Try to build a container for testing and development of pgpg, similar to these:
 - https://github.com/EasyGnuPG/egpg-ds
 - https://github.com/EasyGnuPG/ggpg-ds

Needs to replace `egpg` with `pgpg` everywhere here: https://github.com/EasyGnuPG/pgpg-ds

Then maybe installing some python packages on Dockerfile, like these: https://github.com/EasyGnuPG/ggpg-ds/blob/bionic/Dockerfile#L26

**Comment by dashohoxha** [comment]
If you think that Python development does not need this for development and testing (because it has virtual environment etc.), it is OK.
But I thought that it may be better to work on a clean and isolated environment.

**Comment by diveshuttam** [comment]
Virtual environments help with various versions of python itself. For trying on various versions of debian and gpgme bindings it would be good to have containers also.

**Comment by diveshuttam** [comment]
closed with https://github.com/EasyGnuPG/pgpg-ds/pull/3

**Comment by diveshuttam** [comment]
Container is now invalid and needs a few updates.

**Comment by diveshuttam** [comment]
closed by EasyGnuPG/pgpg-ds#5 EasyGnuPG/pgpg-ds#6
