### ISSUE TITLE
Interface for pgpg

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#21]
Creating a basic interface (in form of defining functions/classes) helps in visualizing the project as a whole.
We can add/remove them later as necessary but still a skeleton helps in initial direction.
Will add functions along with their doc strings. We will fill these with definition as and when needed.
Designing functions together helps in maintaining consistency in naming and other things.
This is specifically better for this project as we already have the known functionality that we have to implement (through egpg). So, there won't be much changes to the interface part.

Three subtasks for this:
- [x] the interactive interface (the command line - like taking input from the user, writing/reading file, displaying help etc.)
- [ ] library interface (functions that deliver the core functionality like encrypting the file and returning the data , fetching list of contact and returning the list etc)
- [ ] The Key/User class (We don't require much of object orientation but for keys/user it classes will help)

**Comment by dashohoxha** [comment]
> The Key/User class

By the way, what is a "User"?
I don't think that OOP will be much useful for such a small project.

If I had to implement it myself, first I would just try to translate the existing code from bash to python. Later I would look for any refactoring and making the code better.
Have you studied the code of `egpg`? If you just try to imitate it in python, you can get easily a working program, no need for big designs or starting everything from scratch.

**Comment by diveshuttam** [comment]
>By the way, what is a "User"?
@sourabhtk37 mentioned this in one of the pr (#18) as far as I interpreted this, in terms of egpg this represents the context of egpg (the .egpg folder, the configuration and the key belonging to the context etc.) (Correct me if I am wrong)
 
>I don't think that OOP will be much useful for such a small project.
I expect most of the code be just in terms of modules. As we also want to expose this as a library, a class may expose the things in a bit better way.

>If I had to implement it myself, first I would just try to translate the existing code from bash to python. >Later I would look for any refactoring and making the code better.
>Have you studied the code of egpg? If you just try to imitate it in python, you can get easily a working ?>program, no need for big designs or starting everything from scratch.
I am planning for the same. I expect most of the code to be on the lines of `egpg` only. As @sourabhtk37 suggested, using a mix of both would be good so I think we can try this out. I don't think it would add much to the structuring as at max there would be a couple of classes.

Also if both of you suggest, for now we can use the classes exposed by the GPGME library (Context and Key). They have the most of required attributes. (Though they lack in methods). And maybe later create classes if and when needed.

**Comment by sourabhtk37** [comment]
Yes, please always use existing classes/methods if they fulfil the use-case. Else just inherit them and add methods. This types of scenarios is where OOP comes in handy. 
But I'm just suggesting OOPs for those things as it might be useful for extending more features and yes as you mentioned, it will have better APIs. It won't add much complexity to the project but rather help in structuring it better.

**Comment by dashohoxha** [comment]
> for now we can use the classes exposed by the GPGME library (Context and Key). They have the most of required attributes. (Though they lack in methods). And maybe later create classes if and when needed.

This is exactly what I have in mind. No need to do a big design right now. Add classes later if needed.

**Comment by diveshuttam** [comment]
closed for now due to change of plans
