### ISSUE TITLE
Update seal.sh

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#32]
https://github.com/EasyGnuPG/pgpg/blob/gnupg-2.2/src/cmd/seal.sh

https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/seal.sh#L32

create and call seal.py which achieves the functionality

**Comment by diveshuttam** [comment]
Checkout the following for retrieving keys from key server
https://github.com/dgladkov/python-hkp

**Comment by diveshuttam** [comment]
https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00

**Comment by dashohoxha** [comment]
Divesh, maybe there is a reason why GPGME does not support keyservers. As far as I understand, the keyserver infrastructure is a bit old and outdated and has some problems. There are projects and attempts to replace it with other key-sharing infrastructures that are better and more suitable than it. So, don't spend too much time with it. Just try to solve the problem as quick as possible.

You can also use `gpg` to retrieve the missing keys and bypass this problem, as I suggested previously. We can return later to fix and improve this solution.
The best thing would be to develop a better keyserver infrastructure, but this can be the topic of another GSoC project, or even a larger project.

**Comment by diveshuttam** [comment]
Yup I felt so, I'll wrap this off today in the best way it seems to me. Just added it for reference if someone else visits this.
