### ISSUE TITLE
Update contact/search.sh

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#42]
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/contact/search.sh#L25

**Comment by diveshuttam** [comment]
@dashohoxha This involves keyserver, I am postponing this for now and also #41 . We will update this after I am able to implement keyserver functionality. Mostly after I do the gui part.
I Hope this is ok.

**Comment by dashohoxha** [comment]
It is OK.
And now that I think about it, some other `gpg` commands that we have replaced previously, actually have been too simple. So we could have actually keep them in `gpg`, since the risk of breaking the functionality of these commands in the future releases of `gpg` is very low.
