### ISSUE TITLE
Update key/list.sh

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#47]
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/key/list.sh#L38

https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/key/list.sh#L42

some scripts from #28 #40 can be same

**Comment by diveshuttam** [comment]
@dashohoxha the above functions support --colons and --raw. Is supporting them required? I checked the existing code, they are not already being used. Also I don't think they are of any help to the user. They might have been added for help for a programmer. 
Also if we want to support some programmable options maybe I could add them in better way. I feel that even egpg's current output format in `key: value` form is better to program to than using --with-colons

**Comment by dashohoxha** [comment]
The option `--raw` means using the `gpg` output, so you don't have to replace this.
Also the `--colons` format is gpg specific, and you don't have to replace this either.
You only need to replace the function `print_key`, or the last part of the script.
