### ISSUE TITLE
Creating new GPGME wrapper or using an existing one?

### ISSUE THREAD

**Issue by vnev** [EasyGnuPG/pgpg#5]
Would an existing Python wrapper around the GPGME library be used, or will we be writing our own wrapper for GPGME? @dashohoxha

**Comment by sourabhtk37** [comment]
Better to use existing ones. If it doesn't cover the use cases, you can contribute to the wrapper.

**Comment by dashohoxha** [comment]
@vnev This is just a question and should be better discussed on the forum: https://github.com/orgs/EasyGnuPG/teams/egpg, instead of creating an issue.
I agree with the answer of @sourabhtk37.

**Comment by diveshuttam** [comment]
GPGME provides [official bindings for Python](https://packages.debian.org/sid/python3-gpg), we plan to use them only. Existing wrappers like [PYME](https://github.com/adversary-org/pyme3) , and [PYGPGME](https://github.com/rshk/pygpgme) are no longer being actively developed. 
You can find few more details regarding this in my [GSoC proposal draft](https://tinyurl.com/diveshuttam-GSoC18-proposal
).
