### ISSUE TITLE
Update key/revcert.sh

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#51]
https://github.com/EasyGnuPG/pgpg/blob/d108baf68dc2eb6de3d360b4bb1e06f2017d0946/src/cmd/key/revcert.sh#L21-L23

**Comment by diveshuttam** [comment]
Hi @dashohoxha I am not able to find a way to achieve this in gpgme. There is no command within the interact interface itself, which achieves generation of revocation certificate.  I don't find a way of achieving the functionality of `--gen-revoke` argument passed to the interact.

**Comment by dashohoxha** [comment]
Maybe you can ask on gnupg-devel about this.

**Comment by diveshuttam** [comment]
refer: https://lists.gnupg.org/pipermail/gnupg-devel/2018-July/033832.html

**Comment by dashohoxha** [comment]
We can close this task.

Also, my opinion is that there is no advantage in replacing `gpg` calls with python GPGME calls. In other applications they may be useful for sign/verify, encryption/decryption and other simple use cases. But in the case of `egpg` I don't see any benefit.

More details here: https://lists.gnupg.org/pipermail/gnupg-devel/2018-July/033836.html

I don't know your opinion about this. If you agree, then as soon as we close all the remaining tasks, we can move to `egpg` (for adding a GUI etc.).

**Comment by diveshuttam** [comment]
Yup done though I added a wontfix label but closing it is better as it cannot be fixed as per the info on gnupg devel
