### ISSUE TITLE
Invite other people to help

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/pgpg#52]
@diveshuttam you have done a great job with defining the changes that need to be made.
If you wish, you can mark some of them with the label "help wanted" or "help is welcome", so that other people may try to help and get involved. Hopefully this may also result in finishing all the tasks sooner.

If someone (@EasyGnuPG/egpg) would like to try one of these tasks, he should first assign it to himself, then create a branch and start a pull request. This way we can be informed and avoid working on the same task.

**Comment by diveshuttam** [comment]
I have assigned 3 tasks to myself. And for now marked key commands and some others as help wanted. Will see what others are interested in if we have more people interested will mark other issues as help wanted as necessary.

**Comment by dashohoxha** [comment]
@EasyGnuPG/egpg here is the list of the tasks that you can give a try:
https://github.com/EasyGnuPG/pgpg/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
You can pickup one of them if you wish.
