### ISSUE TITLE
Add try except blocks to python code

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#57]
I have mostly relied on egpg to provide correct data to python bindings.
Like the file passed always exists and key passed is correct etc.

At a later point we need to check this in python scripts also. Like consider a case when file is deleted between checking by egpg and then its use by python script.

Also expectations from gpgme bindings are not well documented and I don't know which may pop up. This is important aspect that will be revealed while exhaustive testing. For now I am just focussing on getting pgpg working inside the container and just checking for a few basic tests.

**Comment by dashohoxha** [comment]
> I have mostly relied on egpg to provide correct data to python bindings. Like the file passed always exists and key passed is correct etc. At a later point we need to check this in python scripts also. Like consider a case when file is deleted between checking by egpg and then its use by python script.

You should check on the python script only those things that are related to gpg. For example does the given key exist or not, is it valid or not, etc. This is not usually done on the bash script and it relies on the `gpg` command to check this cases and to output error messages if something is wrong.

If a check is done on the bash script (for example the given file exists or not), don't check it again on the python script. The case that you mention is exaggerated. You can check the file existence in python code, and it can be removed before you open it. The possibility is very small but it can happen. So, don't consider such cases.

I think that the best strategy is to rely on the exceptions. You try to run a python code, and if it fails you catch the exception and print an error message. This should work even if you don't check the input. You basically pass the responsibility for checking the correctness of the input data to gpgme. If it does not do it properly, then it should be fixed. You can submit a bug report about it and even you may help fixing it.
