### ISSUE TITLE
Add confirmation while egpg key delete

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#59]
'egpg key delete' does not ask for confirmation now, It also deletes $GPG_KEY if the first parameter passed ($1) is empty. It would be better if we ask for a confirmation.

refer EasyGnuPG/egpg#55

**Comment by dashohoxha** [comment]
There are two issues here.
Create a reminder list so that we can discuss and resolve them at the end.
For the time being let us keep the behavior of `egpg` unchanged, because this is not the focus of what we are doing currently.

**Comment by dashohoxha** [comment]
We can close this in favor of this: https://github.com/EasyGnuPG/egpg/issues/55
