### ISSUE TITLE
Make tests pass

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#63]
Update tests to make them pass on pgpg also

**Comment by diveshuttam** [comment]
t03 always fails for the first time (no keys found) I run it inside the container with clean tests directory. It but passes the second time(when there are already trash and other directories created).

**Comment by dashohoxha** [comment]
This is strange, because this line should be executed before the test cases start (and it should extend the expiration time):
https://github.com/EasyGnuPG/pgpg/blob/gnupg-2.2/tests/t03-init.t#L5

**Comment by diveshuttam** [comment]
Update: it is not because of trash but mainly because of changes in the tests/gnupg directory after running for the first time. Certain files are created which are not already there in the commits. The test passes for all subsequent time we run it.

**Comment by diveshuttam** [comment]
I think there is something wrong with the order, the scripts copies the tests/gnupg directory to trash first and then renews the key (with tests/gnupg as home). I think this is creating the problem
