### ISSUE TITLE
Add tests for key split

### ISSUE THREAD

**Issue by diveshuttam** [EasyGnuPG/pgpg#74]
add tests which were removed in #71 
Will require configuring users in the container. Have a look at https://github.com/EasyGnuPG/egpg/issues/56

**Comment by dashohoxha** [comment]
Add them to `egpg` instead (if you are going to add them).

**Comment by dashohoxha** [comment]
We can close this as well, in favor of this: https://github.com/EasyGnuPG/egpg/issues/56
