### ISSUE TITLE
Research and test various Python libraries/tools about GnuPG

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/pgpg#8]
Here are some relevant tools and libraries that I could find. Probably you can find some more.
 - https://github.com/rshk/pygpgme
 - https://github.com/adversary-org/pyme3
 - https://github.com/diafygi/openpgp-python
 - https://github.com/dlitz/pycrypto
 - https://github.com/dlitz/pycrypto
 - https://github.com/isislovecruft/python-gnupg
 - https://github.com/singpolyma/OpenPGP-Python
 - https://github.com/Hasimir/python-gnupg
 - https://github.com/SecurityInnovation/PGPy
 - http://files.au.adversary.org/crypto/GPGMEpythonHOWTOen.html
 - https://dev.gnupg.org/source/gpgme/browse/master/lang/python/docs/GPGMEpythonHOWTOen.org
 - https://www.gnupg.org/documentation/manuals/gpgme/

**Comment by diveshuttam** [comment]
Considering that pgpg will deal with the user's gpg keys. It is important for it(and the libraries on which it is based on) to be secure. This in turn requires the bindings to be actively maintained. I went through all of the above links. The official bindings seem the best fit at this point as they are being maintained the most frequently and recently.

**Comment by vnev** [comment]
I too agree with @diveshuttam

**Comment by diveshuttam** [comment]
I think we can close this now. I expect the official bindings to work out fine.
