### ISSUE TITLE
Create deb packages for egpg and pgpg

### ISSUE THREAD

**Issue by dashohoxha** [EasyGnuPG/pgpg#82]
- [ ] Find some good tutorials about how to create and submit debian packages.
- [ ] Find relevant mailing lists about creating and maintaining debian packages and subscribe.
- [ ] Build the packages and submit to debian.

**Comment by dashohoxha** [comment]
- http://tldp.org/HOWTO/html_single/Debian-Binary-Package-Building-HOWTO/
- https://debian-handbook.info/browse/stable/sect.building-first-package.html
- https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf
- https://www.debian.org/doc/manuals/maint-guide/
- https://wiki.debian.org/Packaging

**Comment by dashohoxha** [comment]
- https://www.debian.org/doc/manuals/debmake-doc/ch04.en.html
- https://www.debian.org/doc/manuals/debmake-doc/ch08.en.html

**Comment by diveshuttam** [comment]
`debmake` docs are good but still quite extensive. It uses a lot of new things and I am a bit stuck in making all things work on my pc. After some efforts I was able to complete basic tutorial on the container and create a [simple deb package for egpg](https://github.com/diveshuttam/GSoC18/tree/gh-pages/code/builds). 
Though I had to start from chapter 1 to get the tools working. I think I'll give it one more day and if it doesn't work out well, I'll switch over to GUI for this week. I think i'll find that more interesting and productive. 
Will return to this later.

**Comment by dashohoxha** [comment]
> I am a bit stuck in making all things work on my pc

You are not alone. I have been reading docs and trying for about 10 days and I still have not figured out all the things. You can give a try to this approach: 
 - https://github.com/dashohoxha/pw/blob/master/deb.sh

If it works, leave it there and come back later to make things better.

> I'll switch over to GUI for this week. I think i'll find that more interesting and productive.

:+1:

**Comment by dashohoxha** [comment]
Done: https://github.com/EasyGnuPG/egpg/blob/gnupg-2.2/deb.sh
